version: '3.8'

services:

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      REACT_APP_API_URL: "http://backend:3000"
    working_dir: /app

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mutual_fund"
      RAPIDAPI_KEY: "your-rapidapi-key"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mutual_fund
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
